### PR TITLE
Feature GitHub.3

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/21/2023, 3:36:24 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6942148321/attempts/1))
Directory: 'migrations'
  Files:
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
migrate db

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/21/2023, 3:48:34 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6942338226/attempts/1))
Directory: 'migrations'
  Files:
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Pull request merged**
