### PR TITLE
Feature jira.1

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|❌|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


✅ **[DryRun]Migrations successful** 1/16/2024, 1:21:42 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7538518140/attempts/1)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|❌|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


✅ **[DryRun]Migrations successful** 1/16/2024, 2:54:32 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7538518140/attempts/2)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
JIRA Ticket: KAN-32
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|❌|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


✅ **[DryRun]Migrations successful** 1/16/2024, 2:59:15 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7538518140/attempts/3)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by rahuldimri** [comment]
test comment

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason: pull_request_review.submitted
✅ **[DryRun]Migrations successful** 1/16/2024, 3:08:53 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7539668649/attempts/1)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
**Lint Errors**
*Directory*: `migrations/mg1`
: Error: postgres: scanning system variables: dial tcp: lookup postgres on 127.0.0.53:53: server misbehaving
*Directory*: `migrations/mg2`
: Error: postgres: scanning system variables: dial tcp: lookup postgres on 127.0.0.53:53: server misbehaving

❌ **[DryRun]Migrations failed** 1/18/2024, 11:22:53 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7565920418/attempts/1)
> No migrations available

*Directory*: **migrations/mg2**: No migration available


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
    -- No migration available

-- DIRECTORY: migrations/mg2
    -- No migration available
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|✅|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


❌ **[DryRun]Migrations failed** 1/18/2024, 1:27:08 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7566929901/attempts/1)
> No migrations available

*Directory*: **migrations/mg2**: No migration available


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
    -- No migration available

-- DIRECTORY: migrations/mg2
    -- No migration available
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|✅|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


❌ **[DryRun]Migrations failed** 1/18/2024, 1:28:34 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7566929901/attempts/2)
> Error: postgres: scanning system variables: EOF

*Directory*: **migrations/mg2**: No migration available


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
    -- No migration available

-- DIRECTORY: migrations/mg2
    -- No migration available
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
JIRA Ticket: KAN-32
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|✅|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


✅ **[DryRun]Migrations successful** 1/18/2024, 1:29:54 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7566929901/attempts/3)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
JIRA Ticket: KAN-32
**Lint Errors**
*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20231220071838_columns.sql|Dropping non-virtual column "config_type"|[DS103](https://atlasgo.io/lint/analyzers#DS103)|0|
|✅|20231220071838_columns.sql|Renaming column "type" to "prop_type"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|44|


✅ **[DryRun]Migrations successful** 1/18/2024, 1:34:27 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7566974042/attempts/2)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_configs.sql|2|-|-|
|✅|20231220071838_columns.sql|3|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);


-- DIRECTORY: migrations/mg2
-- File: 20231219131522_configs.sql
CREATE TABLE
  config (id int primary key, name varchar(100));
CREATE TABLE
  props (
    id int primary key,
    config_id int not null,
    name int not null,
    value text,
    config_type varchar(100),
    type varchar(100),
    is_active boolean not null default true,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_columns.sql
ALTER table props DROP column config_type;
ALTER table props rename column "type" to prop_type;
ALTER table props add column update_at timestamptz not null default now ();
```
</details>

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Pull request merged**
