### PR TITLE
changes

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/21/2023, 9:15:28 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: 'migrations'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/22/2023, 11:28:38 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: 'migrations'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/22/2023, 11:31:32 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: 'migrations'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/22/2023, 11:33:15 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: 'migrations'
  Files: NA

**Comment by rahuldimri** [comment]
sample

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/22/2023, 11:50:50 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): No migrations available
Directory: 'migrations'
  Files: NA

**Comment by rahuldimri** [comment]
db migrate dry-run11

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 11:55:05 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 12:02:51 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 12:05:37 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 12:06:24 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 12:08:16 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
@rahuldimri hi

**Comment by varunnayal** [comment]
Executed By: @varunnayal
**[DryRun] Migrations successful** 11/22/2023, 12:11:45 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
**[DryRun] Migrations successful** 11/22/2023, 12:12:16 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
**[DryRun] Migrations successful** 11/22/2023, 12:12:41 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
**[DryRun] Migrations successful** 11/22/2023, 12:13:26 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
**[DryRun] Migrations successful** 11/22/2023, 12:13:40 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations successful** 11/22/2023, 12:16:45 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/22/2023, 12:17:53 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
div

**Comment by divyakakroo** [comment]
db migrate

**Comment by varunnayal** [comment]
abc

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/22/2023, 12:45:52 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6954063325/attempts/1))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql
    - 20231120142300.sql
    - 20231120142301.sql
    - 20231120142408.sql
    - 20231121130827.sql

**Comment by varunnayal** [comment]
abc

**Comment by varunnayal** [comment]
aaa

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/22/2023, 12:53:08 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
- 20231017080505.sql
- 20231017081057.sql
- 20231120142300.sql
- 20231120142301.sql
- 20231120142408.sql
- 20231121130827.sql

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/22/2023, 12:55:13 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
- 20231017080505.sql
- 20231017081057.sql
- 20231120142300.sql
- 20231120142301.sql
- 20231120142408.sql
- 20231121130827.sql

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/22/2023, 12:56:25 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
- 20231017080505.sql
- 20231017081057.sql
- 20231120142300.sql
- 20231120142301.sql
- 20231120142408.sql
- 20231121130827.sql

**Comment by varunnayal** [comment]
aaa

**Comment by varunnayal** [comment]
abc

**Pull request closed without merging**
