### PR TITLE
Feature GitHub only

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Review by divyakakroo — APPROVED** [review]

**Review by divyakakroo — APPROVED** [review]

**Review by rahuldimri — APPROVED** [review]

**Review by divyakakroo — APPROVED** [review]

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/19/2023, 5:47:55 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ connect ECONNREFUSED 13.233.220.134:16096
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/20/2023, 12:14:03 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: '.'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/20/2023, 12:35:38 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: '.'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 4:43:19 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 4:45:08 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ getaddrinfo ENOTFOUND base
Directory: '.'
  Files: NA

**Pull request closed without merging**
