### PR TITLE
Feature GitHub.2

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 1:22:39 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6927042728/attempts/1)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 1:28:25 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6927086426/attempts/1)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:26:59 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928357746/attempts/1)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:41:46 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928357746/attempts/2)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:42:24 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/1)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:47:31 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/2)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:49:51 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/3)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:56:14 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/4)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 3:59:44 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/5)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Comment by varunnayal** [comment]
**[DryRun] Migrations failed** 11/20/2023, 4:02:21 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6928555801/attempts/6)): Dir=tmp/__migrations__ getaddrinfo EAI_AGAIN base
Directory: '.'
  Files: NA

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/20/2023, 5:07:03 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6929534065/attempts/1))
Directory: '.'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql

**Comment by varunnayal** [comment]
**[DryRun] Migrations successful** 11/20/2023, 5:14:03 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6929534065/attempts/2))
Directory: 'migrations'
  Files:
    - 20231017080505.sql
    - 20231017081057.sql

**Pull request closed without merging**
