### PR TITLE
feature: atlas integration

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations successful** 11/28/2023, 2:02:41 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/7010234085/attempts/1))
Directory: 'migrations'
  Files:
- 20231127200108.sql

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations failed** 11/28/2023, 8:32:20 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ spawn atlas ENOENT
Directory: 'migrations'
  Files:
- 20231127200108.sql
Directory: 'undefined'
  Files: NA

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations successful** 11/28/2023, 8:33:59 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined))
Directory: 'migrations'
  Files:
- 20231127200108.sql

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations failed** 11/28/2023, 8:35:17 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): Dir=tmp/__migrations__ spawn atlas ENOENT
Directory: 'migrations'
  Files:
- 20231127200108.sql
Directory: 'undefined'
  Files: NA

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations failed** 11/28/2023, 8:37:38 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): No migrations available
Directory: 'migrations'
  Files:
- 123123122.sql

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations failed** 11/28/2023, 8:50:21 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): No migrations available
Directory: 'migrations'
  Files:
- 123123122.sql

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations failed** 11/28/2023, 8:50:59 AM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/1/attempts/undefined)): No migrations available
Directory: 'migrations'
  Files:
- 123123122.sql

**Comment by rahuldimri** [comment]
abc

**Comment by varunnayal** [comment]
abc

**Comment by varunnayal** [comment]
abc

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.synchronize
**[DryRun] Migrations successful** 11/28/2023, 12:10:39 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/7015130977/attempts/2))

- Directory: **'migrations'**
```
Migrating to version 20231127200108 from 20231124071442 (1 migrations in total):

  -- migrating version 20231127200108
    -> ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
  -- ok (3.656µs)

  -------------------------
  -- 1.578007512s
  -- 1 migrations 
  -- 1 sql statements
```

**Comment by rahuldimri** [comment]
db migrate

**Comment by divyakakroo** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate dry-run

**Review by rahuldimri — APPROVED** [review]

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/28/2023, 12:13:21 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/7015164349/attempts/1))

- Directory: **'migrations'**
```
Migrating to version 20231127200108 from 20231124071442 (1 migrations in total):

  -- migrating version 20231127200108
    -> ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
  -- ok (4.588µs)

  -------------------------
  -- 1.619561936s
  -- 1 migrations 
  -- 1 sql statements
```

**Comment by varunnayal** [comment]
db migrate

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/28/2023, 12:14:55 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/7015174157/attempts/1))

- Directory: **'migrations'**
```
Migrating to version 20231127200108 from 20231124071442 (1 migrations in total):

  -- migrating version 20231127200108
    -> ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
  -- ok (4.579µs)

  -------------------------
  -- 1.570090083s
  -- 1 migrations 
  -- 1 sql statements
```

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 11:28:02 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postgres://admin:secret@0.tcp.in.ngrok.io:10032/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: postgres: scanning system variables: dial tcp 13.233.220.134:10032: connect: connection refused
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:43:50 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postgres://root:secret@0.tcp.in.ngrok.io:10032/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: postgres: scanning system variables: dial tcp 3.6.115.64:10032: connect: connection refused
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:44:34 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postgres://root:secret@0.tcp.in.ngrok.io:10032/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: postgres: scanning system variables: dial tcp 3.6.115.64:10032: connect: connection refused
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:45:08 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postgres://root:secret@0.tcp.in.ngrok.io:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/migrate: connected database is not clean: found schema "repack". baseline version or allow-dirty is required
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:49:15 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:54:06 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:55:13 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 12:56:29 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 1:04:20 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 1:05:15 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> *Reason*: Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url
*Directory*: **migrations/migrations**: No migration available

**Pull request closed without merging**
