### PR TITLE
feat: schema changes

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
**Lint Errors**
*Directory*: `migrations/mg1`
: spawn atlas ENOENT
*Directory*: `migrations/mg2`
: spawn atlas ENOENT

❌ **[DryRun]Migrations failed** 2/1/2024, 9:43:57 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> spawn atlas ENOENT

*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2**: No migration available


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1
    -- No migration available

-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2
    -- No migration available
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
JIRA Ticket: KAN-40
**Lint Errors**
*Directory*: `migrations/mg1`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20240201150824_drop_user_age_index.sql|Dropping index "idx_users_name" non-concurrently causes write locks on the "users" table|[PG102](https://atlasgo.io/lint/analyzers#PG102)|22|
|❌|20240201150922_session_data_col_rename.sql|Renaming column "data" to "s_data"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|0|


✅ **[DryRun]Migrations successful** 2/1/2024, 9:46:47 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1
-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
JIRA Ticket: KAN-40
**Lint Errors**
*Directory*: `migrations/mg1`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20240201150824_drop_user_age_index.sql|Dropping index "idx_users_name" non-concurrently causes write locks on the "users" table|[PG102](https://atlasgo.io/lint/analyzers#PG102)|22|
|❌|20240201150922_session_data_col_rename.sql|Renaming column "data" to "s_data"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|0|

*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|Modifying nullable column "value" to non-nullable might fail in case it contains NULL values|[MF104](https://atlasgo.io/lint/analyzers#MF104)|0|


✅ **[DryRun]Migrations successful** 2/1/2024, 10:04:55 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1
-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
**Lint Errors**
*Directory*: `migrations/mg1`
: spawn atlas ENOENT
*Directory*: `migrations/mg2`
: spawn atlas ENOENT

❌ **[DryRun]Migrations failed** 2/1/2024, 11:21:49 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> spawn atlas ENOENT

*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2**: No migration available


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1
    -- No migration available

-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2
    -- No migration available
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.opened
JIRA Ticket: KAN-40
**Lint Errors**
*Directory*: `migrations/mg1`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20240201150824_drop_user_age_index.sql|Dropping index "idx_users_name" non-concurrently causes write locks on the "users" table|[PG102](https://atlasgo.io/lint/analyzers#PG102)|22|
|❌|20240201150922_session_data_col_rename.sql|Renaming column "data" to "s_data"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|0|

*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|Modifying nullable column "value" to non-nullable might fail in case it contains NULL values|[MF104](https://atlasgo.io/lint/analyzers#MF104)|0|


✅ **[DryRun]Migrations successful** 2/1/2024, 11:22:50 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg1
-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason: pull_request_review.submitted
✅ **[DryRun]Migrations successful** 2/1/2024, 11:29:49 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7745571618/attempts/1)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231219131522_user_and_session.sql|2|-|-|
|✅|20231220071838_add_index.sql|2|-|-|
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20231219131522_user_and_session.sql
CREATE TABLE
  users (id int primary key, name varchar(100), age int);
CREATE TABLE
  sessions (
    id int primary key,
    user_id int not null,
    data text not null,
    created_at timestamptz not null default now ()
  );

-- File: 20231220071838_add_index.sql
create index concurrently idx_users_name on users(name);
create index concurrently idx_users_age on users(age);

-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason: pull_request.synchronize
JIRA Ticket: KAN-40
**Lint Errors**
*Directory*: `migrations/mg1`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|❌|20240201150824_drop_user_age_index.sql|Dropping index "idx_users_name" non-concurrently causes write locks on the "users" table|[PG102](https://atlasgo.io/lint/analyzers#PG102)|22|
|❌|20240201150922_session_data_col_rename.sql|Renaming column "data" to "s_data"|[BC102](https://atlasgo.io/lint/analyzers#BC102)|0|

*Directory*: `migrations/mg2`
| Skipped | File | Error | Error Code | Position |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|Modifying nullable column "value" to non-nullable might fail in case it contains NULL values|[MF104](https://atlasgo.io/lint/analyzers#MF104)|0|


✅ **[DryRun]Migrations successful** 2/1/2024, 11:34:53 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7745636693/attempts/1)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason: pull_request_review.submitted
✅ **[DryRun]Migrations successful** 2/1/2024, 11:35:50 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7745651717/attempts/1)
*Directory*: **migrations/mg1**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201150824_drop_user_age_index.sql|1|-|-|
|✅|20240201150922_session_data_col_rename.sql|1|-|-|

*Directory*: **migrations/mg2**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20240201151538_props_value_non_null.sql|1|-|-|
|✅|20240201151719_props_deactivate_column.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations/mg1
-- File: 20240201150824_drop_user_age_index.sql
drop index idx_users_name;

-- File: 20240201150922_session_data_col_rename.sql
alter table sessions rename column data to s_data;


-- DIRECTORY: migrations/mg2
-- File: 20240201151538_props_value_non_null.sql
alter table props alter column value set NOT NULL;

-- File: 20240201151719_props_deactivate_column.sql
ALTER table props add column deactivated_on timestamptz null;
```
</details>

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Pull request closed without merging**
