### PR TITLE
feature: atlas integration

### PR DESCRIPTION
**Pull request by varunnayal**

### CODE REVIEW

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌
**[DryRun] Migrations failed** 12/12/2023, 1:41:23 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌**[DryRun] Migrations failed** 12/12/2023, 1:45:17 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌ **[DryRun] Migrations failed** 12/12/2023, 1:46:20 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> Process "atlas migrate apply --dir file://tmp/__migrations__ --url postg://root:secret@www.example.com:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/sqlclient: unknown driver "postg". See: https://atlasgo.io/url

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌ **[DryRun] Migrations failed** 12/12/2023, 1:47:45 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> Process "atlas migrate apply --dir file://tmp/__migrations__ --url postgres://root:secret@0.tcp.in.ngrok.io:10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public --dry-run" exited with code 1
Error: sql/migrate: connected database is not clean: found schema "repack". baseline version or allow-dirty is required

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌ **[DryRun] Migrations failed** 12/12/2023, 2:28:59 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> "[{"Name":"20231017080505.sql","Version":"20231017080505","Start":"2023-12-12T08:58:58.088135323Z","End":"2023-12-12T08:58:58.278843861Z","Applied":["CREATE TABLE \"public\".\"cities\" (\n  \"id\" text NOT NULL,\n  \"created_at\" timestamptz NOT NULL,\n  \"updated_at\" timestamptz NOT NULL,\n  \"is_active\" boolean NULL DEFAULT true,\n  \"name\" character varying(100) NOT NULL,\n  PRIMARY KEY (\"id\")\n);"]},{"Name":"20231017081057.sql","Version":"20231017081057","Start":"2023-12-12T08:58:58.279099741Z","End":"2023-12-12T08:58:58.464709767Z","Applied":["CREATE TYPE \"public\".\"city_category_enum\" AS ENUM ('Twin', 'Mega', 'Garden');","ALTER TABLE \"public\".\"cities\" ADD COLUMN \"category\" \"public\".\"city_category_enum\" NOT NULL;"]},{"Name":"20231120142300.sql","Version":"20231120142300","Start":"2023-12-12T08:58:58.464712475Z","End":"2023-12-12T08:58:58.653643646Z","Applied":["CREATE TABLE \"public\".\"friends\" (\n  \"user_id\" text NOT NULL,\n  \"friend_id\" text NOT NULL\n);"]},{"Name":"20231120142301.sql","Version":"20231120142301","Start":"2023-12-12T08:58:58.65364498Z","End":"2023-12-12T08:58:58.832105913Z","Applied":["insert into\n  friends (user_id, friend_id)\nvalues\n  (3, 4),\n  (4, 5)"]},{"Name":"20231120142408.sql","Version":"20231120142408","Start":"2023-12-12T08:58:58.832110079Z","End":"2023-12-12T08:58:59.035962739Z","Applied":["CREATE UNIQUE INDEX \"idx_user_id_friend_id\" ON \"public\".\"friends\" (\"user_id\", \"friend_id\");"]},{"Name":"20231121130827.sql","Version":"20231121130827","Start":"2023-12-12T08:58:59.035964114Z","End":"2023-12-12T08:58:59.236641756Z","Applied":["ALTER TABLE \"public\".\"cities\" ADD COLUMN \"status\" text NULL;","ALTER TABLE \"public\".\"friends\" ADD COLUMN \"active\" boolean NULL;"]},{"Name":"20231123054431.sql","Version":"20231123054431","Start":"2023-12-12T08:58:59.236646964Z","End":"2023-12-12T08:58:59.443186883Z","Applied":["ALTER TABLE \"public\".\"cities\" DROP COLUMN \"status\";"]},{"Name":"20231124071442.sql","Version":"20231124071442","Start":"2023-12-12T08:58:59.443188842Z","End":"2023-12-12T08:58:59.633165491Z","Applied":["ALTER TYPE \"public\".\"city_category_enum\" ADD VALUE 'Dumb';"]},{"Name":"20231127200108.sql","Version":"20231127200108","Start":"2023-12-12T08:58:59.633169616Z","End":"2023-12-12T08:58:59.633728085Z","Applied":["ALTER TABLE \"public\".\"cities\" ADD COLUMN \"status\" character varying(20) NOT NULL;"]}]"

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
❌ **[DryRun] Migrations failed** 12/12/2023, 2:31:35 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> "[{"Name":"20231017080505.sql","Version":"20231017080505","Start":"2023-12-12T09:01:32.925346351Z","End":"2023-12-12T09:01:33.109722875Z","Applied":["CREATE TABLE \"public\".\"cities\" (\n  \"id\" text NOT NULL,\n  \"created_at\" timestamptz NOT NULL,\n  \"updated_at\" timestamptz NOT NULL,\n  \"is_active\" boolean NULL DEFAULT true,\n  \"name\" character varying(100) NOT NULL,\n  PRIMARY KEY (\"id\")\n);"]},{"Name":"20231017081057.sql","Version":"20231017081057","Start":"2023-12-12T09:01:33.109819085Z","End":"2023-12-12T09:01:33.307379986Z","Applied":["CREATE TYPE \"public\".\"city_category_enum\" AS ENUM ('Twin', 'Mega', 'Garden');","ALTER TABLE \"public\".\"cities\" ADD COLUMN \"category\" \"public\".\"city_category_enum\" NOT NULL;"]},{"Name":"20231120142300.sql","Version":"20231120142300","Start":"2023-12-12T09:01:33.307383403Z","End":"2023-12-12T09:01:33.499275987Z","Applied":["CREATE TABLE \"public\".\"friends\" (\n  \"user_id\" text NOT NULL,\n  \"friend_id\" text NOT NULL\n);"]},{"Name":"20231120142301.sql","Version":"20231120142301","Start":"2023-12-12T09:01:33.499279529Z","End":"2023-12-12T09:01:33.685021079Z","Applied":["insert into\n  friends (user_id, friend_id)\nvalues\n  (3, 4),\n  (4, 5)"]},{"Name":"20231120142408.sql","Version":"20231120142408","Start":"2023-12-12T09:01:33.685023621Z","End":"2023-12-12T09:01:33.865708699Z","Applied":["CREATE UNIQUE INDEX \"idx_user_id_friend_id\" ON \"public\".\"friends\" (\"user_id\", \"friend_id\");"]},{"Name":"20231121130827.sql","Version":"20231121130827","Start":"2023-12-12T09:01:33.865710741Z","End":"2023-12-12T09:01:34.040143366Z","Applied":["ALTER TABLE \"public\".\"cities\" ADD COLUMN \"status\" text NULL;","ALTER TABLE \"public\".\"friends\" ADD COLUMN \"active\" boolean NULL;"]},{"Name":"20231123054431.sql","Version":"20231123054431","Start":"2023-12-12T09:01:34.040145825Z","End":"2023-12-12T09:01:34.223190032Z","Applied":["ALTER TABLE \"public\".\"cities\" DROP COLUMN \"status\";"]},{"Name":"20231124071442.sql","Version":"20231124071442","Start":"2023-12-12T09:01:34.223192574Z","End":"2023-12-12T09:01:34.765247477Z","Applied":["ALTER TYPE \"public\".\"city_category_enum\" ADD VALUE 'Dumb';"]},{"Name":"20231127200108.sql","Version":"20231127200108","Start":"2023-12-12T09:01:34.76525006Z","End":"2023-12-12T09:01:34.7655814Z","Applied":["ALTER TABLE \"public\".\"cities\" ADD COLUMN \"status\" character varying(20) NOT NULL;"]}]"

*Directory*: **migrations/migrations**: No migration available

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:41:36 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:42:38 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:43:28 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|


<details><summary>SQL Statements</summary>
-- DIRECTORY: migrations
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:44:59 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|


<details><summary>SQL Statements</summary>
```-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
```</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:45:47 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|


<details><summary>SQL Statements</summary>
```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
```</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:46:48 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:49:00 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|
|✅|20231017081057.sql|2|NA|NA|
|✅|20231120142300.sql|1|NA|NA|
|✅|20231120142301.sql|1|NA|NA|
|✅|20231120142408.sql|1|NA|NA|
|✅|20231121130827.sql|2|NA|NA|
|✅|20231123054431.sql|1|NA|NA|
|✅|20231124071442.sql|1|NA|NA|
|✅|20231127200108.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
--File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);
--File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;
--File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);
--File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)
--File: 20231120142408.sql
CREATE UNIQUE INDEX "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");
--File: 20231121130827.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" text NULL;
ALTER TABLE "public"."friends" ADD COLUMN "active" boolean NULL;
--File: 20231123054431.sql
ALTER TABLE "public"."cities" DROP COLUMN "status";
--File: 20231124071442.sql
ALTER TYPE "public"."city_category_enum" ADD VALUE 'Dumb';
--File: 20231127200108.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:50:21 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|
|✅|20231017081057.sql|2|NA|NA|
|✅|20231120142300.sql|1|NA|NA|
|✅|20231120142301.sql|1|NA|NA|
|✅|20231120142408.sql|1|NA|NA|
|✅|20231121130827.sql|2|NA|NA|
|✅|20231123054431.sql|1|NA|NA|
|✅|20231124071442.sql|1|NA|NA|
|✅|20231127200108.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");

-- File: 20231121130827.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" text NULL;
ALTER TABLE "public"."friends" ADD COLUMN "active" boolean NULL;

-- File: 20231123054431.sql
ALTER TABLE "public"."cities" DROP COLUMN "status";

-- File: 20231124071442.sql
ALTER TYPE "public"."city_category_enum" ADD VALUE 'Dumb';

-- File: 20231127200108.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
```
</details>

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 11:51:31 AM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|
|✅|20231017081057.sql|2|NA|NA|
|✅|20231120142300.sql|1|NA|NA|
|✅|20231120142301.sql|1|NA|NA|
|✅|20231120142408.sql|1|NA|NA|
|✅|20231121130827.sql|2|NA|NA|
|✅|20231123054431.sql|1|NA|NA|
|✅|20231124071442.sql|1|NA|NA|
|✅|20231127200108.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX CONCURRENTLY "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");

-- File: 20231121130827.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" text NULL;
ALTER TABLE "public"."friends" ADD COLUMN "active" boolean NULL;

-- File: 20231123054431.sql
ALTER TABLE "public"."cities" DROP COLUMN "status";

-- File: 20231124071442.sql
ALTER TYPE "public"."city_category_enum" ADD VALUE 'Dumb';

-- File: 20231127200108.sql
ALTER TABLE "public"."cities" ADD COLUMN "status" character varying(20) NOT NULL;
```
</details>

**Comment by divyakakroo** [comment]
abc

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
✅ **[DryRun] Migrations successful** 12/13/2023, 12:15:34 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|
|✅|20231017081057.sql|2|NA|NA|
|✅|20231120142300.sql|1|NA|NA|
|✅|20231120142301.sql|1|NA|NA|
|✅|20231120142408.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX CONCURRENTLY "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");
```
</details>

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
✅ **[DryRun] Migrations successful** 12/13/2023, 12:26:12 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|NA|NA|
|✅|20231017081057.sql|2|NA|NA|
|✅|20231120142300.sql|1|NA|NA|
|✅|20231120142301.sql|1|NA|NA|
|✅|20231120142408.sql|1|NA|NA|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX CONCURRENTLY "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");
```
</details>

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
✅ **[DryRun] Migrations successful** 12/13/2023, 1:32:00 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|-|-|
|✅|20231017081057.sql|2|-|-|
|✅|20231120142300.sql|1|-|-|
|✅|20231120142301.sql|1|-|-|
|✅|20231120142408.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: /Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX CONCURRENTLY "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");
```
</details>

**Comment by varunnayal** [comment]
Executed By: @rahuldimri
Reason=pull_request_review.submitted
✅ **[DryRun] Migrations successful** 12/13/2023, 1:33:11 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
*Directory*: **migrations**
| Status | File | Total Statements | Error | Error Statement |
| --- | --- | --- | --- | --- |
|✅|20231017080505.sql|1|-|-|
|✅|20231017081057.sql|2|-|-|
|✅|20231120142300.sql|1|-|-|
|✅|20231120142301.sql|1|-|-|
|✅|20231120142408.sql|1|-|-|


<details><summary>SQL Statements</summary>

```sql
-- DIRECTORY: migrations
-- File: 20231017080505.sql
CREATE TABLE "public"."cities" (
  "id" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "is_active" boolean NULL DEFAULT true,
  "name" character varying(100) NOT NULL,
  PRIMARY KEY ("id")
);

-- File: 20231017081057.sql
CREATE TYPE "public"."city_category_enum" AS ENUM ('Twin', 'Mega', 'Garden');
ALTER TABLE "public"."cities" ADD COLUMN "category" "public"."city_category_enum" NOT NULL;

-- File: 20231120142300.sql
CREATE TABLE "public"."friends" (
  "user_id" text NOT NULL,
  "friend_id" text NOT NULL
);

-- File: 20231120142301.sql
insert into
  friends (user_id, friend_id)
values
  (3, 4),
  (4, 5)

-- File: 20231120142408.sql
CREATE UNIQUE INDEX CONCURRENTLY "idx_user_id_friend_id" ON "public"."friends" ("user_id", "friend_id");
```
</details>

**Comment by divyakakroo** [comment]
12 db migrate

**Comment by varunnayal** [comment]
db m

**Comment by varunnayal** [comment]
> db migrate
> 
> ❌ **Migrations failed** 12/13/2023, 2:12:05 PM [View](https://github.com/varunnayal-org/go-svc/actions/runs/7177394943/attempts/1)
> 
> > Command failed: atlas migrate apply --dir file://tmp/**migrations** --url postgres://root:[secret@0.tcp.in.ngrok.io](mailto:secret@0.tcp.in.ngrok.io):10160/d1?sslmode=disable --format "{{ json .Applied }}" --revisions-schema public
> > Error: sql/migrate: connected database is not clean: found schema "repack". baseline version or allow-dirty is required
> 
> _Directory_: **/Users/varunnayal/code/personal/db-migrations/go-svc.master/migrations**: No migration available
> 
> SQL Statements

**Comment by varunnayal** [comment]
dkfj

**Comment by varunnayal** [comment]
db sdf

**Comment by varunnayal** [comment]
abc

**Comment by varunnayal** [comment]
> Hi


| ColA | ColB | ColC |
| --- | --- | --- |
|a\|b|b\|d|c|

**Pull request closed without merging**
