### PR TITLE
Feature GitHub.4

### PR DESCRIPTION
**Pull request by varunnayal**
Teams:
```
dba: divyakakroo,varunnayal
data: rahuldimri,varunnayal
go-svc-team: varunnayal
```

db.migration.json
```
{
  "baseDirectory": "./migrations",
  "approvalTeams": ["dba"],
  "ownerTeams": ["go-svc-team"],
  "databases": [
    {
      "directory": ".",
      "envName": "DB_URL"
    }
  ]
}
```

### CODE REVIEW

**Comment by varunnayal** [comment]
Executed By: @varunnayal
Reason=pull_request.opened
**[DryRun] Migrations successful** 11/22/2023, 5:37:02 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6957035792/attempts/1))
Directory: 'migrations'
  Files:
- 20231017080505.sql
- 20231017081057.sql
- 20231120142300.sql
- 20231120142301.sql
- 20231120142408.sql
- 20231121130827.sql

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Comment by divyakakroo** [comment]
db migrate

**Review by divyakakroo — APPROVED** [review]

**Comment by varunnayal** [comment]
Executed By: @divyakakroo
Reason=pull_request_review.submitted
**[DryRun] Migrations successful** 11/22/2023, 8:18:21 PM ([Execution](https://github.com/varunnayal-org/go-svc/actions/runs/6958924245/attempts/1))
Directory: 'migrations'
  Files:
- 20231017080505.sql
- 20231017081057.sql
- 20231120142300.sql
- 20231120142301.sql
- 20231120142408.sql
- 20231121130827.sql

**Comment by divyakakroo** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate

**Comment by rahuldimri** [comment]
db migrate dry-run

**Comment by rahuldimri** [comment]
db migrate dry-run

**Comment by rahuldimri** [comment]
db migrate dry-run

**Comment by rahuldimri** [comment]
db migrate dry-run

**Comment by varunnayal** [comment]
db migrate

**Comment by varunnayal** [comment]
db migrate

**Pull request merged**
